/* set if background is active/loadavle (0=no, 1=yes) */
ACT_BG_SUB_STREET = 1
ACT_BG_ROOF	  = 1
ACT_BG_BANK	  = 1
ACT_BG_TOWER  	= 1
ACT_BG_SOUL	  = 1
ACT_BG_BELL	  = 1
ACT_BG_GRAVE  = 1
ACT_BG_BRIDGE = 1
ACT_BG_TEMPLE = 1
ACT_BG_THRONE = 1

ACT_BG_LADDER = 1
ACT_BG_BIO	= 1
ACT_BG_COIN = 1
ACT_BG_VS = 1
ACT_BG_BUYIN = 1


SCX = 100

/* GLOBAL EQUATES */
NULL_IRQSKYE = 444
END_LIST = 0
SKIP_BAKMOD = 1
FORCE_EXIT = -1
CENTER_X = -2

	.extern bakmods			
	.extern worldtlx		
	.extern worldtlx1		
	.extern worldtlx2		
	.extern worldtlx3		
	.extern worldtlx4		
	.extern worldtlx5		
	.extern worldtlx6		
	.extern worldtlx7		
	.extern worldtlx8		
	.extern worldtly		
	.extern worldtly1		
	.extern worldtly2		
	.extern worldtly3		
	.extern worldtly4		
	.extern worldtly5		
	.extern worldtly6		
	.extern worldtly7		
	.extern worldtly8		
	.extern scrollx			
	.extern scrollx1		
	.extern scrollx2		
	.extern scrollx3		
	.extern scrollx4		
	.extern scrollx5		
	.extern scrollx6		
	.extern scrollx7		
	.extern scrollx8		
	.extern objlst			
	.extern objlst2			
	.extern baklst0			
	.extern baklst1			
	.extern baklst2			
	.extern baklst3			
	.extern baklst4			
	.extern baklst5			
	.extern baklst6			
	.extern baklst7			
	.extern baklst8			
	.extern baklst9			

	.extern objlst_t		
	.extern baklst1_t		
	.extern baklst2_t		
	.extern baklst3_t		
	.extern baklst4_t		
	.extern baklst5_t		
	.extern baklst6_t		
	.extern baklst7_t		
	.extern baklst8_t		

	.extern worldtlx8_t		
	.extern worldtlx7_t		
	.extern worldtlx6_t		
	.extern worldtlx5_t		
	.extern worldtlx4_t		
	.extern worldtlx3_t		
	.extern worldtlx2_t		
	.extern worldtlx1_t		
	.extern worldtlx_t		

	.extern calla_return	
	.extern skew_7			
	.extern skew_8			
	.extern floor_code		
	.extern shadow_p1p2		
	.extern use_next_y		
	.extern use_worldtly_t	
	.extern check_only_t	
	.extern use_worldtly	

